### ISSUE TITLE
Inhalt der configuration.php

### ISSUE THREAD

**Issue by olafzieger** [jug-berlin/joomla.berlin#1]
Wie gehen wir mit der Joomla-Konfiguration um? Die Inhalte ändern ja schon das Verhalten der Installation (URL-Rewrite). Was meint Ihr?

![bildschirmfoto 2015-01-23 um 12 30 33](https://cloud.githubusercontent.com/assets/2371334/5873910/ffdb43d4-a2fb-11e4-8d44-c6f12ad5b391.png)

**Comment by olafzieger** [comment]
Es legt ja jeder eine andere configuration.php an. Oder, hab ich das falsch verstanden?

**Comment by patjun** [comment]
Ich persönlich arbeite beim entwickeln mit abgeschalteten SEF Urls. Erst beim testen schalte ich sie ein, um die Änderungen zu testen. Da ja jeder seine eigene configuration.php hat, sollte das auch keine Probleme geben.

**Comment by olafzieger** [comment]
also legt sich jeder seine an … alles klar

**Comment by patjun** [comment]
Da da auch die Datenbanken drin stehen macht das keinen Sinn sie gemeinsam zu nutzen.
