### ISSUE TITLE
bootstrap.min.js wird doppelt geladen

### ISSUE THREAD

**Issue by neoriva** [jug-berlin/joomla.berlin#2]
Auf den meisten Seiten wird nach dem templates/frontend/js/bootstrap.min.js das media/jui/js/bootstrap.min.js geladen. Daduch funktioniert z.B. das Menu Toggle nicht mehr.
Lustig: auf "Kontakt" ist alles schick - andere Script Reihenfolge!

**Comment by olafzieger** [comment]
Das ist leider typisch für das blanktemplate. Ich glaube das kann man nur umgehen, indem man die Module ausfindig macht, die mit folgendem Aufruf:

``` PHP
JHtml::_('bootstrap.framework');
```

das Joomla-eigene Bootstrap laden.
Man müsste es dann mit einem override überschreiben beziehungsweise entfernen.

**Comment by olafzieger** [comment]
Ich habe auch neulich von folgende Erweiterung gelesen hab sie aber noch nicht ausgiebig testen können. 
JQuery easy 
http://extensions.joomla.org/extension/jquery-easy
Es steuert glaube ich auch das Laden des Bootstrap Framework.

**Comment by patjun** [comment]
Hab hier auch was gefunden:
https://github.com/Bloggerschmidt/Blank/issues/54

**Comment by patjun** [comment]
Ich glaube das hier könnte es auch sein:
http://blank.vc/de/forum/bootstrap,-jquery,-dropdown-menu-bug-parent-verschwindet

**Comment by neoriva** [comment]
Merci für den Input!
Das Joomla bootstrap.js wird auch durch diesen Ausdruck aufgerufen:
JHtml::_('bootstrap.tooltip')
z.B in mod_login und mod_finder
per override entfernt und soweit OK!
